In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
from sqlalchemy import create_engine
con = create_engine('postgresql+psycopg2://fbeyeuhk:s7E6hfo6pU5K1KhDKF3v8Zw_WeqyQKMy@hattie.db.elephantsql.com/fbeyeuhk')  

/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)


In [ ]:
def select(sql):
    return pd.read_sql(sql, con)

Задание: 1 (Serge I: 2002-09-30)
Найдите номер модели, скорость и размер жесткого диска для всех ПК стоимостью менее 500 дол. Вывести: model, speed и hd


In [ ]:
sql = '''
SELECT pc.model,
       pc.speed,
       pc.hd
FROM pc AS pc
WHERE price<500'''
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

Задание: 2 (Serge I: 2002-09-21)
Найдите производителей принтеров. Вывести: maker

In [ ]:
sql = '''
SELECT DISTINCT maker
FROM product
WHERE TYPE ='Printer'
'''
select(sql)

maker
0     A
1     D
2     E

Задание: 3 (Serge I: 2002-09-30)
Найдите номер модели, объем памяти и размеры экранов ПК-блокнотов, цена которых превышает 1000 дол.

In [ ]:
sql = '''SELECT model,
       ram,
       screen
FROM laptop
WHERE price>1000
'''
select(sql)

model  ram  screen
0  1750  128      14
1  1298   64      15
2  1752  128      14

Задание: 4 (Serge I: 2002-09-21)
Найдите все записи таблицы Printer для цветных принтеров.

In [ ]:
sql = '''SELECT *
FROM printer
WHERE color ='y'
'''
select(sql)

code model color type  price
0     2  1433     y  Jet  270.0
1     3  1434     y  Jet  290.0

Задание: 5 (Serge I: 2002-09-30)
Найдите номер модели, скорость и размер жесткого диска ПК, имеющих 12x или 24x CD и цену менее 600 дол.


In [ ]:
sql = '''SELECT model,
       speed,
       hd
FROM pc
WHERE (cd='12x'
       OR cd ='24x')
  AND (price<600)
'''
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

Задание: 6 (Serge I: 2002-10-28)
Для каждого производителя, выпускающего ПК-блокноты c объёмом жесткого диска не менее 10 Гбайт, найти скорости таких ПК-блокнотов. Вывод: производитель, скорость.


In [ ]:
sql = '''
SELECT DISTINCT p.maker,
                l.speed
FROM product AS p
JOIN laptop AS l ON p.model = l.model
WHERE l.hd>=10'''
select(sql)

maker  speed
0     A    750
1     A    450
2     A    600
3     B    750

Задание: 7 (Serge I: 2002-11-02)
Найдите номера моделей и цены всех имеющихся в продаже продуктов (любого типа) производителя B (латинская буква).

In [ ]:
sql = '''SELECT DISTINCT p.model, l.price from product as p
JOIN laptop as l on l.model = p.model
WHERE p.maker ='B'
UNION ALL

SELECT DISTINCT p.model, pc.price from product as p
JOIN pc as pc on pc.model = p.model
WHERE p.maker ='B'
UNION ALL

SELECT DISTINCT p.model, pr.price from product as p
JOIN printer as pr on pr.model = p.model
WHERE p.maker ='B'

'''
select(sql)

model   price
0  1750  1200.0
1  1121   850.0

Задание: 8 (Serge I: 2003-02-03)
Найдите производителя, выпускающего ПК, но не ПК-блокноты./)

In [ ]:
sql = '''
WITH pc_maker AS
  (SELECT DISTINCT p.maker
   FROM product AS p
   WHERE p.type='PC' ),
     lp_maker AS
  (SELECT DISTINCT p.maker
   FROM product AS p
   WHERE p.type='Laptop' )
SELECT pm.*
FROM pc_maker AS pm
WHERE pm.maker not in
    (SELECT *
     FROM lp_maker)
'''
select(sql)

maker
0     E

апдейт решения с использованием except

In [ ]:
sql = '''
SELECT p.maker from product as p
WHERE p.type='PC'
EXCEPT
SELECT p.maker from product as p
WHERE p.type='Laptop'
'''
select(sql)

maker
0     E


Задание: 9. Найдите производителей ПК с процессором не менее 450 Мгц. Вывести: Maker

In [ ]:
sql = '''SELECT DISTINCT p.maker
FROM product AS p
JOIN pc AS pc ON p.model = pc.model
WHERE pc.speed >= 450
'''
select(sql)

maker
0     B
1     E
2     A

Задание: 10 (Serge I: 2002-09-23)
Найдите модели принтеров, имеющих самую высокую цену. Вывести: model, price


In [ ]:
sql = '''
WITH max_price AS
  (SELECT max(p.price) as price
   FROM printer AS p)
SELECT p.model,
       p.price
FROM printer AS p
WHERE p.price in
    (SELECT *
     FROM max_price)
'''
select(sql)

model  price
0  1276  400.0
1  1288  400.0

Задание: 11 (Serge I: 2002-11-02)
Найдите среднюю скорость ПК.

In [ ]:
sql ='''
SELECT AVG(pc.speed) AS avg_speed
FROM pc AS pc
'''
select(sql)

avg_speed
0  608.333333

Задание: 12 (Serge I: 2002-11-02)
Найдите среднюю скорость ПК-блокнотов, цена которых превышает 1000 дол.

In [ ]:
sql = '''
SELECT avg(l.speed)
FROM laptop AS l
WHERE l.price>1000
'''
select(sql)


avg
0  700.0

Задание: 13 (Serge I: 2002-11-02)
Найдите среднюю скорость ПК, выпущенных производителем A.

In [ ]:
sql ='''
SELECT avg(pc.speed)
FROM product AS p
JOIN pc ON pc.model = p.model
WHERE p.maker = 'A'
'''
select(sql)

avg
0  606.25

Задание: 14 (Serge I: 2002-11-05)
Найдите класс, имя и страну для кораблей из таблицы Ships, имеющих не менее 10 орудий.


In [ ]:
sql = '''SELECT sh.class,
       sh.name,
       c.country
FROM Ships AS sh
JOIN Classes AS c ON sh.class = c.class
WHERE c.numGuns >=10
'''
select(sql)

class            name country
0       Tennessee      California     USA
1  North Carolina  North Carolina     USA
2       Tennessee       Tennessee     USA
3  North Carolina      Washington     USA
4  North Carolina    South Dakota     USA

Задание: 15 (Serge I: 2003-02-03)
Найдите размеры жестких дисков, совпадающих у двух и более PC. Вывести: HD

In [ ]:
sql = '''
SELECT hd
FROM pc
GROUP BY hd
HAVING count(1)>=2
'''
select(sql)

hd
0   8.0
1  20.0
2   5.0
3  14.0
4  10.0

Задание: 16 (Serge I: 2003-02-03)
Найдите пары моделей PC, имеющих одинаковые скорость и RAM. В результате каждая пара указывается только один раз, т.е. (i,j), но не (j,i), Порядок вывода: модель с большим номером, модель с меньшим номером, скорость и RAM.


In [ ]:
sql = '''
SELECT DISTINCT t.model,
                l.model,
                l.speed,
                l.ram
FROM pc AS t,
     pc AS l
WHERE t.speed = l.speed
  AND t.ram = l.ram
  AND t.model > l.model
ORDER BY t.model
'''
select(sql)

model model  speed  ram
0  1233  1121    750  128
1  1233  1232    500   64
2  1260  1232    500   32

Задание: 17 (Serge I: 2003-02-03)
Найдите модели ПК-блокнотов, скорость которых меньше скорости каждого из ПК.
Вывести: type, model, speed


In [ ]:
sql = '''
WITH min_speed AS
  (SELECT MIN(pc.speed) AS speed
   FROM pc AS pc)
SELECT DISTINCT p.type,
                l.model,
                l.speed
FROM Product AS p
JOIN laptop AS l ON p.model = l.model
WHERE l.speed<
    (SELECT *
     FROM min_speed)
'''
select(sql)

type model  speed
0  Laptop  1298    350

Задание: 18 (Serge I: 2003-02-03)
Найдите производителей самых дешевых цветных принтеров. Вывести: maker, price

In [ ]:
sql = '''
WITH printers AS
  (SELECT DISTINCT p.maker,
                   pr.price
   FROM Product AS p
   JOIN printer AS pr ON p.model = pr.model
   WHERE pr.color = 'y')
SELECT t.*
FROM printers AS t
WHERE t.price =
    (SELECT MIN(t.price) AS price
     FROM printers AS t)
'''
select(sql)

maker  price
0     D  270.0

Задание: 19 (Serge I: 2003-02-13)
Для каждого производителя, имеющего модели в таблице Laptop, найдите средний размер экрана выпускаемых им ПК-блокнотов.
Вывести: maker, средний размер экрана.

In [ ]:
sql = '''
SELECT p.maker,
       avg(screen) AS Avg_screen
FROM Product AS p
JOIN Laptop AS l ON p.model = l.model
GROUP BY p.maker
'''
select(sql)

maker  avg_screen
0     B        14.0
1     C        12.0
2     A        13.0

Задание: 20 (Serge I: 2003-02-13)
Найдите производителей, выпускающих по меньшей мере три различных модели ПК. Вывести: Maker, число моделей ПК.

In [ ]:
sql = '''
SELECT p.maker,
       count(1) AS COUNT
FROM Product AS p
WHERE p.type='PC'
GROUP BY p.maker
HAVING count(1)>2
'''
select(sql)

maker  count
0     E      3

Задание: 21 (Serge I: 2003-02-13)
Найдите максимальную цену ПК, выпускаемых каждым производителем, у которого есть модели в таблице PC.
Вывести: maker, максимальная цена.

In [ ]:
sql = '''
SELECT p.maker,
       MAX(pc.price) AS max_price
FROM Product AS p
JOIN pc AS pc ON pc.model=p.model
WHERE p.type='PC'
GROUP BY p.maker
'''
select(sql)

maker  max_price
0     A      980.0
1     B      850.0
2     E      350.0

Задание: 22 (Serge I: 2003-02-13)
Для каждого значения скорости ПК, превышающего 600 МГц, определите среднюю цену ПК с такой же скоростью. Вывести: speed, средняя цена.


In [ ]:
sql = '''
SELECT pc.speed,
       avg(price) AS avg_price
FROM pc AS pc
WHERE pc.speed > 600
GROUP BY pc.speed
'''
select(sql)

speed  avg_price
0    900      980.0
1    750      900.0
2    800      970.0

Задание: 23 (Serge I: 2003-02-14)
Найдите производителей, которые производили бы как ПК
со скоростью не менее 750 МГц, так и ПК-блокноты со скоростью не менее 750 МГц.
Вывести: Maker


In [ ]:
sql ='''
SELECT pr.maker
FROM Product AS pr
JOIN pc AS pc ON pr.model=pc.model
WHERE pc.speed>=750 INTERSECT
  SELECT pr.maker
  FROM Product AS pr
  JOIN Laptop AS l ON pr.model=l.model WHERE l.speed>=750
'''
select(sql)

maker
0     B
1     A

Задание: 24 (Serge I: 2003-02-03)
Перечислите номера моделей любых типов, имеющих самую высокую цену по всей имеющейся в базе данных продукции.

In [ ]:
sql = '''
WITH model_price AS
  (SELECT pc.model,
          pc.price
   FROM pc
   UNION ALL SELECT l.model,
                    l.price
   FROM Laptop AS l
   UNION ALL SELECT p.model,
                    p.price
   FROM printer AS p)
SELECT DISTINCT mp.model
FROM model_price AS mp
WHERE mp.price in
    (SELECT MAX(mp.price)
     FROM model_price AS mp)
'''
select(sql)

model
0  1750

25 
Найдите производителей принтеров, которые производят ПК с наименьшим объемом RAM и с самым быстрым процессором среди всех ПК, имеющих наименьший объем RAM. Вывести: Maker


In [ ]:
sql = '''
WITH least_ram AS
  (SELECT pc.model,
          pc.speed
   FROM pc
   WHERE pc.ram in
       (SELECT MIN(pc.ram)
        FROM pc) ),

     fastest_pc AS
  (SELECT lr.model
   FROM least_ram AS lr
   WHERE lr.speed in
       (SELECT MAX(lr.speed)
        FROM least_ram AS lr) ),
        
     makers AS
  (SELECT pr.maker
   FROM product AS pr
   JOIN fastest_pc AS fp ON fp.model=pr.model)
SELECT pr.maker

FROM product AS pr
WHERE pr.type = 'Printer'

INTERSECT

SELECT *
FROM makers
'''
select(sql)

maker
0     A
1     E

Задание: 26 (Serge I: 2003-02-14)
Найдите среднюю цену ПК и ПК-блокнотов, выпущенных производителем A (латинская буква). Вывести: одна общая средняя цена.




In [ ]:
sql = '''
WITH pc_a AS
  (SELECT pc.model,
          pc.price
   FROM product AS pr
   JOIN pc ON pr.model = pc.model
   WHERE pr.maker = 'A'),

     laptop_a AS
  (SELECT l.model,
          l.price
   FROM product AS pr
   JOIN laptop AS l ON pr.model = l.model
   WHERE pr.maker = 'A'),

     pc_lp AS
  (SELECT *
   FROM pc_a
   UNION ALL
   SELECT *
   FROM laptop_a)

SELECT AVG(PRICE)
FROM pc_lp
'''
select(sql)

avg
0  754.166667

Задание: 27 (Serge I: 2003-02-03)
Найдите средний размер диска ПК каждого из тех производителей, которые выпускают и принтеры. Вывести: maker, средний размер HD.

In [ ]:
sql = '''
WITH printer_makers AS
  (SELECT DISTINCT pr.maker
   FROM product AS pr
   WHERE pr.type ='Printer')
SELECT pr.maker,
       AVG(pc.hd)
FROM product AS pr
JOIN pc ON pc.model=pr.model
WHERE pr.maker in
    (SELECT *
     FROM printer_makers)
GROUP BY pr.maker

'''
select(sql)

maker    avg
0     E  10.00
1     A  14.75

Задание: 28 (Serge I: 2012-05-04)
Используя таблицу Product, определить количество производителей, выпускающих по одной модели.


In [ ]:
sql = '''
with model_list as (
  SELECT pr.maker, count(1) as count from product as pr
  GROUP BY pr.maker
  HAVING count(1) = 1
)

SELECT count(1) as count from model_list

'''
select(sql)

count
0      1

Задание: 29 (Serge I: 2003-02-14)
В предположении, что приход и расход денег на каждом пункте приема фиксируется не чаще одного раза в день [т.е. первичный ключ (пункт, дата)], написать запрос с выходными данными (пункт, дата, приход, расход). Использовать таблицы Income_o и Outcome_o.


In [ ]:
sql = '''
SELECT CASE
         WHEN i.point IS NULL THEN o.point
         ELSE i.point
       end AS point,
       CASE
         WHEN i.date IS NULL THEN o.date
         ELSE i.date
       end AS date,
       i.inc,
       o.OUT
FROM   income_o AS i
       full JOIN outcome_o AS o
              ON o.point = i.point
                 AND o.date = i.date 
'''
select(sql)

point       date      inc       out
0       1 2001-03-22  15000.0       NaN
1       1 2001-03-23  15000.0       NaN
2       1 2001-03-24   3400.0   3663.00
3       1 2001-04-13   5000.0   4490.00
4       1 2001-05-11   4500.0   2530.00
5       2 2001-03-22  10000.0   1440.00
6       2 2001-03-24   1500.0       NaN
7       3 2001-09-13  11500.0   1500.00
8       3 2001-10-02  18000.0       NaN
9       3 2001-09-14      NaN   2300.00
10      2 2001-04-02      NaN   2040.00
11      2 2001-03-29      NaN   7848.00
12      1 2001-03-14      NaN  15348.00
13      1 2001-03-29      NaN   2004.00
14      1 2001-04-11      NaN   3195.04
15      3 2002-09-16      NaN   2150.00
16      1 2001-03-26      NaN   1221.00
17      1 2001-04-27      NaN   3110.00
18      1 2001-03-28      NaN   2075.00

Задание: 30 (Serge I: 2003-02-14)
В предположении, что приход и расход денег на каждом пункте приема фиксируется произвольное число раз (первичным ключом в таблицах является столбец code), требуется получить таблицу, в которой каждому пункту за каждую дату выполнения операций будет соответствовать одна строка.
Вывод: point, date, суммарный расход пункта за день (out), суммарный приход пункта за день (inc). Отсутствующие значения считать неопределенными (NULL).


In [ ]:
sql = '''
WITH income_sum_table
     AS (SELECT i.point,
                i.date,
                Sum(i.inc) AS inc
         FROM   income AS i
         GROUP  BY i.point,
                   i.date),
     outcome_sum_table
     AS (SELECT o.point,
                o.date,
                Sum(o.out) AS out
         FROM   outcome AS o
         GROUP  BY o.point,
                   o.date)
SELECT CASE
         WHEN i.point IS NULL THEN o.point
         ELSE i.point
       END AS point,
       CASE
         WHEN i.date IS NULL THEN o.date
         ELSE i.date
       END AS date,
       o.out,
       i.inc
FROM   income_sum_table AS i
       FULL JOIN outcome_sum_table AS o
              ON o.point = i.point
                 AND i.date = o.date 
'''
select(sql)

point       date       out      inc
0       1 2001-03-24   7163.00   7000.0
1       1 2001-05-11   2530.00   4500.0
2       2 2001-03-24       NaN   3000.0
3       1 2001-03-23       NaN  15000.0
4       1 2001-03-22       NaN  30000.0
5       3 2001-09-13   2700.00   3100.0
6       2 2001-03-22   2880.00  10000.0
7       1 2001-04-13   4490.00  10000.0
8       1 2001-03-14  15348.00      NaN
9       3 2001-09-14   1150.00      NaN
10      1 2001-03-29   4010.00      NaN
11      1 2001-04-11   3195.04      NaN
12      2 2001-04-02   2040.00      NaN
13      1 2001-03-26   1221.00      NaN
14      2 2001-03-29   7848.00      NaN
15      1 2001-03-28   2075.00      NaN
16      1 2001-04-27   3110.00      NaN

Задание: 31 (Serge I: 2002-10-22)
Для классов кораблей, калибр орудий которых не менее 16 дюймов, укажите класс и страну.

In [ ]:
sql ='''
SELECT c.class, c.country from Classes as c
WHERE c.bore>=16
'''
select(sql)

class country
0            Iowa     USA
1  North Carolina     USA
2          Yamato   Japan

Задание: 32 (Serge I: 2003-02-17)
Одной из характеристик корабля является половина куба калибра его главных орудий (mw). С точностью до 2 десятичных знаков определите среднее значение mw для кораблей каждой страны, у которой есть корабли в базе данных.


In [ ]:
sql = '''
WITH countries
     AS (SELECT s.NAME,
                c.country,
                c.bore
         FROM   classes AS c
                JOIN ships AS s
                  ON s.class = c.class
         UNION
         SELECT o.ship,
                c.country,
                c.bore
         FROM   classes AS c
                JOIN outcomes AS o
                  ON o.ship = c.class)
SELECT c.country,
       Round(Cast(( Avg(Pow(c.bore, 3) / 2.0) ) AS NUMERIC), 2) AS average
FROM   countries AS c
GROUP  BY c.country 
'''
select(sql)

country  average
0         USA  1897.78
1     Germany  1687.50
2  Gt.Britain  1687.50
3       Japan  1886.67

Задание: 33 (Serge I: 2002-11-02)
Укажите корабли, потопленные в сражениях в Северной Атлантике (North Atlantic). Вывод: ship.


In [ ]:
sql= '''
SELECT o.ship from Outcomes as o
WHERE o.result in ('sunk') and o.battle='North Atlantic'
'''
select(sql)

ship
0  Bismarck
1      Hood

Задание: 34 (Serge I: 2002-11-04)
По Вашингтонскому международному договору от начала 1922 г. запрещалось строить линейные корабли водоизмещением более 35 тыс.тонн. Укажите корабли, нарушившие этот договор (учитывать только корабли c известным годом спуска на воду). Вывести названия кораблей.


In [ ]:
sql = '''
WITH ships_info
     AS (SELECT s.NAME,
                s.launched,
                c.displacement AS disp
         FROM   ships AS s
                JOIN classes AS c
                  ON c.class = s.class
         WHERE  c.type = 'bb')
SELECT si.NAME
FROM   ships_info AS si
WHERE  si.launched >= 1922
       AND si.disp > 35000 

'''
select(sql)

name
0            Iowa
1        Missouri
2         Musashi
3      New Jersey
4  North Carolina
5      Washington
6       Wisconsin
7          Yamato
8    South Dakota

Задание: 35 (qwrqwr: 2012-11-23)
В таблице Product найти модели, которые состоят только из цифр или только из латинских букв (A-Z, без учета регистра).
Вывод: номер модели, тип модели.


In [ ]:
sql = '''
SELECT pr.model,
       pr.type
FROM   product AS pr
WHERE  ( pr.model NOT LIKE '%[^a-zA-Z]%' )
        OR ( pr.model NOT LIKE '%[^0-9]%' ) 
'''
select(sql)

model     type
0   1121       PC
1   1232       PC
2   1233       PC
3   1260       PC
4   1276  Printer
5   1288  Printer
6   1298   Laptop
7   1321   Laptop
8   1401  Printer
9   1408  Printer
10  1433  Printer
11  1434  Printer
12  1750   Laptop
13  1752   Laptop
14  2113       PC
15  2112       PC

Задание: 36 (Serge I: 2003-02-17)
Перечислите названия головных кораблей, имеющихся в базе данных (учесть корабли в Outcomes).


In [ ]:
sql = '''
SELECT s.name
FROM   ships AS s
WHERE  s.name = s.class
UNION
SELECT o.ship
FROM   outcomes AS o
       JOIN classes AS c
         ON c.class = o.ship 
'''
select(sql)

name
0       Tennessee
1          Yamato
2        Bismarck
3         Revenge
4           Kongo
5          Renown
6  North Carolina
7            Iowa

Задание: 37 (Serge I: 2003-02-17)
Найдите классы, в которые входит только один корабль из базы данных (учесть также корабли в Outcomes).


In [ ]:
sql = '''
WITH ship_classes
     AS (SELECT s.NAME,
                s.class
         FROM   ships AS s
         UNION
         SELECT o.ship,
                c.class
         FROM   outcomes AS o
                JOIN classes AS c
                  ON c.class = o.ship)
SELECT sc.class
FROM   ship_classes AS sc
GROUP  BY sc.class
HAVING Count(1) = 1 

'''
select(sql)

class
0  Bismarck

Задание: 38 (Serge I: 2003-02-19)
Найдите страны, имевшие когда-либо классы обычных боевых кораблей ('bb') и имевшие когда-либо классы крейсеров ('bc').

In [ ]:
sql = '''

SELECT c.country from classes as c
WHERE c.type = 'bb'
INTERSECT
SELECT c.country from classes as c
WHERE c.type = 'bc'

'''
select(sql)

country
0  Gt.Britain
1       Japan

Задание: 39 (Serge I: 2003-02-14)
Найдите корабли, `сохранившиеся для будущих сражений`; т.е. выведенные из строя в одной битве (damaged), они участвовали в другой, произошедшей позже.

Задание: 40 (Serge I: 2012-04-20)
Найти производителей, которые выпускают более одной модели, при этом все выпускаемые производителем модели являются продуктами одного типа.
Вывести: maker, type


In [ ]:
sql = '''
WITH t
     AS (SELECT pr.maker,
                pr.type,
                Count(1) AS cnt
         FROM   product AS pr
         GROUP  BY pr.maker,
                   pr.type),
     res
     AS (SELECT t.maker,
                Count(1)   AS type_count,
                Sum(t.cnt) AS model_sum
         FROM   t
         GROUP  BY t.maker)
SELECT DISTINCT r.maker,
                pr.type
FROM   res AS r
       JOIN product AS pr
         ON pr.maker = r.maker
WHERE  type_count = 1
       AND model_sum > 1 

'''
select(sql)

maker     type
0     D  Printer

Задание: 41 (Serge I: 2019-05-31)
Для каждого производителя, у которого присутствуют модели хотя бы в одной из таблиц PC, Laptop или Printer,
определить максимальную цену на его продукцию.
Вывод: имя производителя, если среди цен на продукцию данного производителя присутствует NULL, то выводить для этого производителя NULL,
иначе максимальную цену

In [ ]:
sql = '''
WITH agg_table
     AS (SELECT pr.maker,
                pr.model,
                pc.price
         FROM   product AS pr
                JOIN pc
                  ON pc.model = pr.model
         UNION ALL
         SELECT pr.maker,
                pr.model,
                p.price
         FROM   product AS pr
                JOIN printer AS p
                  ON p.model = pr.model
         UNION ALL
         SELECT pr.maker,
                pr.model,
                l.price
         FROM   product AS pr
                JOIN laptop AS l
                  ON l.model = pr.model)
SELECT a.maker,
       CASE
         WHEN Max(CASE
                    WHEN( a.price IS NULL ) THEN 1
                    ELSE 0
                  END) = 1 THEN NULL
         ELSE Max(a.price)
       END AS price_max
FROM   agg_table AS a
GROUP  BY a.maker
'''

select(sql)

maker  price_max
0     B     1200.0
1     C      970.0
2     D      400.0
3     E      350.0
4     A     1150.0

Задание: 42 (Serge I: 2002-11-05)
Найдите названия кораблей, потопленных в сражениях, и название сражения, в котором они были потоплены.

In [ ]:
sql = '''
SELECT o.ship, o.battle from outcomes o
where result ='sunk'

'''
select(sql)

ship          battle
0    Bismarck  North Atlantic
1        Fuso  Surigao Strait
2        Hood  North Atlantic
3   Kirishima     Guadalcanal
4  Schamhorst      North Cape
5   Yamashiro  Surigao Strait

Задание: 43 (qwrqwr: 2011-10-28)
Укажите сражения, которые произошли в годы, не совпадающие ни с одним из годов спуска кораблей на воду.

In [ ]:
sql = '''
select b.name from battles as b
where date_part('year',b.date) not in (SELECT s.launched from ships as s)
'''
select(sql)

name
0  #Cuba62a
1  #Cuba62b

Задание: 44 (Serge I: 2002-12-04)
Найдите названия всех кораблей в базе данных, начинающихся с буквы R.


In [ ]:
sql = '''
with names as (
  SELECT s.name from ships as s
  UNION 
  SELECT o.ship from outcomes as o
)
select * from names as n
where n.name like 'R%'

'''
select(sql)


name
0        Ramillies
1       Resolution
2          Revenge
3           Rodney
4        Royal Oak
5          Repulse
6  Royal Sovereign
7           Renown

Задание: 45 (Serge I: 2002-12-04)
Найдите названия всех кораблей в базе данных, состоящие из трех и более слов (например, King George V).
Считать, что слова в названиях разделяются единичными пробелами, и нет концевых пробелов.


In [ ]:
sql = '''
with names as (
  SELECT s.name from ships as s
  UNION 
  SELECT o.ship from outcomes as o
)
select * from names as n
where n.name like '% % %'

'''
select(sql)

name
0  Prince of Wales
1    King George V
2     Duke of York

Задание: 46 Для каждого корабля, участвовавшего в сражении при Гвадалканале (Guadalcanal), вывести название, водоизмещение и число орудий.

In [ ]:
sql = '''
WITH cls
     AS (SELECT s.NAME AS ship,
                c.displacement,
                c.numguns
         FROM   ships AS s
                JOIN classes AS c
                  ON c.class = s.class
         UNION
         SELECT c.class AS ship,
                c.displacement,
                c.numguns
         FROM   classes AS c)
SELECT o.ship,
       c.displacement,
       c.numguns
FROM   outcomes AS o
       LEFT JOIN cls AS c
              ON o.ship = c.ship
WHERE  o.battle = 'Guadalcanal' 


'''
select(sql)

ship  displacement  numguns
0    California         32000       12
1    Washington         37000       12
2     Kirishima         32000        8
3  South Dakota         37000       12

\Задание: 47 (Serge I: 2019-06-07)
Определить страны, которые потеряли в сражениях все свои корабли.

In [ ]:
sql = '''
WITH cls AS
  (SELECT s.name AS ship,
          c.country
   FROM ships AS s
   JOIN classes AS c ON c.class=s.class
   UNION SELECT o.ship AS ship,
                c.country
   FROM classes AS c
   JOIN outcomes AS o ON o.ship=c.class),
     sunked AS
  (SELECT o.ship
   FROM outcomes AS o
   WHERE o.result = 'sunk'),
     agg_table AS
  (SELECT c.*,
          CASE
              WHEN c.ship in
                     (SELECT *
                      FROM sunked) THEN 1
              ELSE 0
          END AS sunked
   FROM cls AS c)
SELECT a.country
FROM agg_table AS a
GROUP BY a.country
HAVING sum(a.sunked)=count(1)


'''
select(sql)

country
0  Germany


Задание: 48 (Serge I: 2003-02-16)
Найдите классы кораблей, в которых хотя бы один корабль был потоплен в сражении.

In [ ]:
sql = '''
SELECT c.class
FROM classes AS c
JOIN outcomes AS o ON o.ship=c.class
WHERE o.result = 'sunk'
UNION
SELECT s.class
FROM ships AS s
JOIN outcomes AS o ON o.ship=s.name
WHERE o.result = 'sunk'
'''

select(sql)

class
0     Kongo
1  Bismarck

Задание: 49 (Serge I: 2003-02-17)
Найдите названия кораблей с орудиями калибра 16 дюймов (учесть корабли из таблицы Outcomes).

In [ ]:
sql = '''
WITH NAMES AS
  (SELECT c.class AS name,
          c.bore
   FROM classes AS c
   JOIN outcomes AS o ON o.ship=c.class
   UNION SELECT s.name,
                c.bore
   FROM ships AS s
   JOIN classes AS c ON c.class=s.class)
SELECT n.name
FROM NAMES AS n
WHERE n.bore = 16

'''
select(sql)

name
0       Wisconsin
1    South Dakota
2      New Jersey
3        Missouri
4      Washington
5            Iowa
6  North Carolina

Задание: 50 (Serge I: 2002-11-05)
Найдите сражения, в которых участвовали корабли класса Kongo из таблицы Ships.


In [ ]:
sql = '''
SELECT DISTINCT o.battle from ships as s
JOIN outcomes as o on s.name=o.ship
where s.class = 'Kongo'

'''
select(sql)

battle
0  Guadalcanal

Задание: 51 (Serge I: 2003-02-17)
Найдите названия кораблей, имеющих наибольшее число орудий среди всех имеющихся кораблей такого же водоизмещения (учесть корабли из таблицы Outcomes).

In [ ]:
sql = '''
WITH NAMES AS
  (SELECT s.name AS ship,
          c.numguns,
          c.displacement
   FROM ships AS s
   JOIN classes AS c ON s.class=c.class
   UNION SELECT o.ship,
                c.numguns,
                c.displacement
   FROM outcomes AS o
   JOIN classes AS c ON c.class = o.ship), rnk AS
  (SELECT *,
          rank() OVER (PARTITION BY n.displacement
                       ORDER BY n.numguns DESC)
   FROM NAMES AS n)
SELECT r.ship
FROM rnk AS r
WHERE rank =1

'''
select(sql)

ship
0   Royal Sovereign
1           Revenge
2         Royal Oak
3         Ramillies
4         Tennessee
5        California
6        Washington
7      South Dakota
8    North Carolina
9          Bismarck
10       New Jersey
11         Missouri
12        Wisconsin
13             Iowa
14          Musashi
15           Yamato